project_id = "vmrtentqpbvvqkgsilgk"

[functions.neuronwriter-api]
verify_jwt = false

[functions.generate-article]
verify_jwt = true

[functions.generate-elementor-template]
verify_jwt = true

[functions.generate-html-export]
verify_jwt = true
