project_id = "vmrtentqpbvvqkgsilgk"

[functions.neuronwriter-api]
verify_jwt = false

[functions.generate-article]
verify_jwt = false

[functions.generate-elementor-template]
verify_jwt = false

[functions.generate-html-export]
verify_jwt = false

[functions.run-migrations]
verify_jwt = false

[functions.wordpress-taxonomies]
verify_jwt = false

[functions.wordpress-publish]
verify_jwt = false
